### ISSUE TITLE
Realize `dessert()` into a separate archive stored locally that contains: a) the .Rmd, b) the .html and .pdf, c) the object as .RData file

### ISSUE THREAD

**Issue by gerkovink** [gerkovink/dessert#4]

**Comment by gerkovink** [comment]
1. Also include `MS Word`
2. Argument to specify path
3. Make sure that an unsaved source file will not render an empty path --> if() solution that defaults to getWD()
4. Communicate where the files are stored in a print to the console.

**Comment by hanneoberman** [comment]
Think about informative naming conventions for Rmd, pdf, HTML and Word files (currently `example`)
